# Generated by Django 3.2.3 on 2021-06-02 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='itemName',
        ),
    ]
